# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notescms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
